/**
 * AlarmAnalyzeView - Alarm intelligent analysis view component
 *
 * Displays alarm intelligent analysis results, supporting two analysis modes:
 * - LLM analysis mode: displays deep analysis text generated by LLM
 * - Statistical mode: displays statistical summary (level distribution, error TopN, trace anomalies, duration anomalies)
 * Supports keyboard scrolling.
 */
import { useState, useMemo, useRef } from "react";
import { Box, Text, useInput } from "ink";
import { type AnalysisResult, type StatisticsSummary } from "../alarmAnalyzer.js";
import { Header } from "./Header.js";
import { Footer } from "./Footer.js";

/** AlarmAnalyzeView props */
interface AlarmAnalyzeViewProps {
  /** Analysis result object */
  result: AnalysisResult;
  /** Query info */
  queryInfo: string;
  /** Back callback */
  onBack: () => void;
}

/** Build statistical analysis text lines */
function buildStatisticsLines(stats: StatisticsSummary): string[] {
  const lines: string[] = [];

  lines.push("=== Statistical Summary ===");
  lines.push(`Total logs: ${stats.totalLogs}`);

  // Level distribution
  const levelParts = Object.entries(stats.levelDistribution)
    .sort((a, b) => {
      const order = ["ERROR", "FATAL", "WARN", "INFO", "DEBUG"];
      return order.indexOf(a[0]) - order.indexOf(b[0]);
    })
    .map(([level, count]) => `${level}: ${count}`);
  if (levelParts.length > 0) {
    lines.push(`  ${levelParts.join("  ")}`);
  }

  // Error Top N
  if (stats.errorPatterns.length > 0) {
    lines.push("");
    lines.push(`Error Top ${stats.errorPatterns.length} patterns:`);
    for (let i = 0; i < stats.errorPatterns.length; i++) {
      const p = stats.errorPatterns[i];
      lines.push(`  ${i + 1}. [${p.count} entries] ${p.pattern}`);
    }
  }

  // Trace errors
  if (stats.traceErrors.length > 0) {
    lines.push("");
    lines.push("Trace anomalies:");
    for (const e of stats.traceErrors) {
      const rate = e.totalCount > 0 ? Math.round((e.errorCount / e.totalCount) * 100) : 0;
      lines.push(`  - ${e.from} → ${e.to}: Error rate ${rate}%`);
    }
  }

  // Duration anomalies
  if (stats.slowCalls.length > 0) {
    lines.push("");
    lines.push("Duration anomalies:");
    for (const c of stats.slowCalls) {
      lines.push(`  - ${c.from} → ${c.to}: Avg ${c.avgDurationMs}ms (P99: ${c.p99DurationMs}ms)`);
    }
  }

  return lines;
}

/** Build LLM analysis text lines */
function buildLLMAnalysisLines(analysisText: string): string[] {
  return analysisText.split("\n");
}

/** Build all display lines */
function buildDisplayLines(result: AnalysisResult): string[] {
  const lines: string[] = [];

  // Top info
  if (result.type === "llm") {
    lines.push(`Analysis mode: LLM (analyzer: ${result.analyzerName}${result.contextName ? `, context: ${result.contextName}` : ""})`);
  } else {
    lines.push("Analysis mode: Statistical (no LLM mapping configured, falling back to statistical summary)");
  }

  if (result.appname) {
    lines.push(`App: ${result.appname}`);
  }

  lines.push("");

  if (result.type === "llm" && result.analysisText) {
    lines.push(...buildLLMAnalysisLines(result.analysisText));
  } else if (result.statistics) {
    lines.push(...buildStatisticsLines(result.statistics));
  }

  return lines;
}

export function AlarmAnalyzeView({ result, queryInfo, onBack }: AlarmAnalyzeViewProps) {
  const [scrollOffset, setScrollOffset] = useState(0);

  const allLines = useMemo(() => buildDisplayLines(result), [result]);

  const terminalHeight = process.stdout.rows || 40;
  const headerLines = 4;
  const footerLines = 3;
  const availableHeight = Math.max(5, terminalHeight - headerLines - footerLines);

  const maxScroll = Math.max(0, allLines.length - availableHeight);
  const safeOffset = Math.min(Math.max(0, scrollOffset), maxScroll);

  const stateRef = useRef({ maxScroll, safeOffset });
  stateRef.current = { maxScroll, safeOffset };

  useInput((input, key) => {
    const s = stateRef.current;

    if (input === "q" || key.escape) {
      onBack();
      return;
    }

    if (key.upArrow || input === "k") {
      setScrollOffset((prev) => Math.max(0, prev - 1));
      return;
    }
    if (key.downArrow || input === "j") {
      setScrollOffset((prev) => Math.min(s.maxScroll, prev + 1));
      return;
    }

    if (key.ctrl && input === "e") {
      setScrollOffset((prev) => Math.min(s.maxScroll, prev + 1));
      return;
    }
    if (key.ctrl && input === "y") {
      setScrollOffset((prev) => Math.max(0, prev - 1));
      return;
    }

    if (input === "g" && !key.ctrl) {
      setScrollOffset(0);
      return;
    }
    if (input === "G" || (input === "g" && key.shift)) {
      setScrollOffset(s.maxScroll);
      return;
    }
  });

  const visibleLines = allLines.slice(safeOffset, safeOffset + availableHeight);
  const headerQueryInfo = `${queryInfo} | ${allLines.length} lines`;
  const footerHints = "↑↓/jk/Ctrl+e/y Scroll g/G top/bottom q back";

  return (
    <Box flexDirection="column" padding={0}>
      <Header title="Alarm Analyze" queryInfo={headerQueryInfo} />

      <Box flexDirection="column" flexGrow={1} paddingX={1}>
        {visibleLines.map((line, i) => {
          // Title line color
          if (line.startsWith("=== ")) {
            return <Text key={i} color="cyan" bold>{line}</Text>;
          }
          if (line.startsWith("Analysis mode:")) {
            return <Text key={i} color="yellow">{line}</Text>;
          }
          if (line.startsWith("App:")) {
            return <Text key={i} color="green">{line}</Text>;
          }
          // Markdown headings
          if (line.startsWith("### ")) {
            return <Text key={i} color="cyan" bold>{line}</Text>;
          }
          if (line.startsWith("## ")) {
            return <Text key={i} color="cyan" bold>{line}</Text>;
          }
          if (line.startsWith("# ")) {
            return <Text key={i} color="cyan" bold>{line}</Text>;
          }
          // Error related
          if (line.includes("Error") || line.includes("ERROR")) {
            return <Text key={i} color="red">{line}</Text>;
          }
          // List items
          if (line.startsWith("  - ")) {
            return <Text key={i} color="yellow">{line}</Text>;
          }
          return <Text key={i}>{line}</Text>;
        })}
      </Box>

      <Footer searchMode={false} searchQuery="" hints={footerHints} />
    </Box>
  );
}
